Import("env")
import libdeps

env = env.Clone()
# This line must contain all paths which have include file
env.Append(CPPPATH=['/Users/admin/Documents/Huy/mongo-addon/10.15.3/include/node', '/Users/admin/Documents/Huy/build/mongo/src/mongo/embedded/mongo_embedded/mongo_addon/include', '/Users/admin/Documents/Huy/mongo-addon/10.15.3/include/node', '/Users/admin/Documents/Huy/mongo-addon/node_modules/node-addon-api', '/Users/admin/Documents/Huy/mongo-addon/10.15.3/deps/v8/include', '/Users/admin/Documents/Huy/mongo-addon/10.15.3/src'])
env.Append(LINKFLAGS=['-shared', '-undefined', 'dynamic_lookup'])

env['LIBDEPS_SHLIBEMITTER'] = libdeps.make_libdeps_emitter(
    'SharedArchive',
    libdeps.dependency_visibility_honored
)

env.Append(LINKFLAGS=['-Wl,-exported_symbols_list,src/mongo/embedded/mongo_embedded/mongo_addon/libmongo_addon.exported_symbols_list'])

env.Library(
    target='mongo-addon',
    source=[
        'mongo-addon.cc',
        'mongo-client.cc',
        'mongo-instance.cc',
        'mongo-lib.cc',
        'mongo-params.cc',
        'mongo-status.cc',
        'wrapper.cc'
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/embedded/mongo_embedded/mongo_embedded'
    ],
    INSTALL_ALIAS=[
        'embedded-addon',
    ],
)



